### ISSUE TITLE
`preserveDecimal` test giving false positive

### ISSUE THREAD

**Issue by bhollan** [learn-co-curriculum/javascript-arithmetic-lab#12]
Test:
```
  it('returns NaN as appropriate', function() {
    expect(isNaN(preserveDecimal('sldkjflksjf'))).toEqual(true)
  })
```
Student code giving false 'pass':
```
function preserveDecimal(n) {
  parseFloat('n')
  return n
}
```

@aturkewi 
[student repo](https://github.com/hyoyou/javascript-arithmetic-lab-js-intro-000/blob/master/index.js#L25)

**Comment by aturkewi** [comment]
Thanks for raising.
Looks like the real problem here is that `expect(preserveDecimal('2.222')).toEqual(2.222)` will pass if the function returns `'2.222'`. Expect's `.toEqual()` is using `==` and `'2.222' == 2.222` will return true. We need to be checking `===` which we can do with `.toBe()`.

I'll put in a PR for it right now.

**Comment by aturkewi** [comment]
And thanks for posting the student code so I could re-create and best understand :)
