### ISSUE TITLE
problem with MakeInt function

### ISSUE THREAD

**Issue by sanober15** [learn-co-curriculum/javascript-arithmetic-lab#22]
Hi I am having trouble with the makeInt function. it won't pass assumes base 10 and return NaN as appropriate

**Comment by rajanpatel1011** [comment]
hi 
make your function wisely like two arguments and one is number which n here and base which is b

**Comment by maxwellbenton** [comment]
Hi @sanober15, 
 
Thank you for this feedback. Sorry to hear you were having difficulty with this lab. We've updated this lesson's instructions and tests so that the instructions are consistent with what is expected in tests and provide additional guidance, which should help prevent confusion for future students.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know!
