### ISSUE TITLE
IDE Keeps Dropping

### ISSUE THREAD

**Issue by lerenah** [learn-co-curriculum/javascript-arithmetic-lab#27]
<img width="1435" alt="screen shot 2018-12-09 at 1 35 55 pm" src="https://user-images.githubusercontent.com/32880751/49701227-9314c900-fbb7-11e8-9f7e-882ba55b1f42.png">

I have a strong wifi signal, so there's no issue there.  I believe it is with the IDE, it keeps disconnecting.  This has happened quite often even while trying to complete other modules.

**Comment by maxwellbenton** [comment]
Hi @lerenahm 

Sorry to hear you were having difficulty with this lab. This issue was reported and resolved in early 2019, which should resolve this issue for future students.
 
We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know about your experience!
