### ISSUE TITLE
JavaScript Arithmetic Lab - misleading statement

### ISSUE THREAD

**Issue by kishore28m** [learn-co-curriculum/javascript-arithmetic-lab#28]
The lesson states the following under the basic math paragraph ,

"At this point, we can fix the first four broken tests: we can define functions add(), subtract(), multiply(), divide() in index.js." 

but the provided index.js file is empty. It looks like the goal is to have students create their own functions. So the above statement should be corrected to indicate that.

**Comment by maxwellbenton** [comment]
Hi @kishore28m,
 
Thank you for this feedback. We've updated this lesson's instructions and tests. We've corrected the instructions so that they are consistent with what is expected in tests and provide additional guidance, which should help prevent confusion for future students.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know!
