### ISSUE TITLE
JavaScript Arithmetic Lab - missing test questions

### ISSUE THREAD

**Issue by edenbenbow** [learn-co-curriculum/javascript-arithmetic-lab#29]
The JavaScript Arithmetic Lab concludes by saying "You're now ready to solve the final two tests in this lab, makeInt(n) and preserveDecimal(n)."

The lab does not specify what the user has to accomplish in makeInt(n) or preserveDecimal(n), nor where the tests should be submitted (I'm assuming index.js). 

This bars the user from moving forward--please change to the same format as previous labs.

**Comment by maxwellbenton** [comment]
Hi @edenbenbow,

Thank you for this feedback. We've updated this lesson's instructions, correcting the instructions so that they are consistent with what is expected in the tests and include additional guidance, which should help prevent confusion for future students.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know!
