### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by gillianedulsa** [learn-co-curriculum/javascript-arithmetic-lab#30]
I am very confused as to what I was supposed to learn. It wanted me to code math equations, however; I don't really think it gave me the proper functions to do so. The "Read Me" ended with saying that we were ready for the next part of the lab, but didn't tell us how to go about it. I failed all of my test and it still allowed me to move on. I am not sure of the purpose of this lesson.

**Comment by bbtodd** [comment]
I think there's a disconnect between the lab and what we learned just prior.  Will just have to move on.

**Comment by ghost** [comment]
Agreed. This section wasn't very clear what it was asking. I had to enter 'learn test' at the beginning so I can see what was expected.

**Comment by maxwellbenton** [comment]
Hi @gillianedulsa,

Thank you for this feedback. We've updated this lesson's instructions and tests, correcting the instructions so that they are consistent with what is expected in tests, which should help prevent confusion for future students. 

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know!
