### ISSUE TITLE
hyperlink no longer valid for incremenetor / decrementor jsforallof.us

### ISSUE THREAD

**Issue by Rpascar1** [learn-co-curriculum/javascript-arithmetic-lab#31]
http://jsforallof.us/2014/07/10/pre-increment-vs-post-increment/
User avatar

link 404's

**Comment by Anthonyntilelli** [comment]
Obligatory not an employee of Flatiron in any way.

Added a alternative link for explanation, 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Increment

**Comment by marcbacodes** [comment]
Link still shows up.

**Comment by Rpascar1** [comment]
On august 6th this was fixed by Anthony tielli

**Comment by Anthonyntilelli** [comment]
@Rpascar1 

The 2 pull request I have submitted were not accepted.  Old link is still in place.  And now old link leads to adverts.

**Comment by Rpascar1** [comment]
Thanks for looking at it again Anthony

**Comment by maxwellbenton** [comment]
Hi @Rpascar1,
 
Thank you for spotting this and providing feedback. We've merged in the PR provided by @Anthonyntilelli   so that this link correctly points to the MDN documentation on incrementing in JavaScript, which should resolve this issue.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know about this! Also, thank you @Anthonyntilelli for the provided fix!
