### ISSUE TITLE
"here" link seems malicious D;

### ISSUE THREAD

**Issue by joshycsm** [learn-co-curriculum/javascript-arithmetic-lab#36]
broken or malicious link? Dx i'm scared.

**Comment by maxwellbenton** [comment]
Hi @joshycsm,

Thank you for spotting this and providing feedback. We've updated this link so that it correctly points to the official MDN documentation on incrementing in JavaScript, which should resolve this issue. 

We apologize for any frustration this may have caused, but appreciate you taking the time to let us know!
